package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.AccountBook;
import cn.ahyc.yjz.model.AccountBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int countByExample(AccountBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int deleteByExample(AccountBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int insert(AccountBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int insertSelective(AccountBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    List<AccountBook> selectByExample(AccountBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    AccountBook selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") AccountBook record, @Param("example") AccountBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int updateByExample(@Param("record") AccountBook record, @Param("example") AccountBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int updateByPrimaryKeySelective(AccountBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int updateByPrimaryKey(AccountBook record);
}