package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.AccountSubject;
import cn.ahyc.yjz.model.AccountSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int countByExample(AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int deleteByExample(AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int insert(AccountSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int insertSelective(AccountSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    List<AccountSubject> selectByExample(AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    AccountSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") AccountSubject record, @Param("example") AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByExample(@Param("record") AccountSubject record, @Param("example") AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByPrimaryKeySelective(AccountSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByPrimaryKey(AccountSubject record);
}