package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.BalanceSheet;
import cn.ahyc.yjz.model.BalanceSheetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BalanceSheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    int countByExample(BalanceSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    int deleteByExample(BalanceSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    int insert(BalanceSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    int insertSelective(BalanceSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    List<BalanceSheet> selectByExample(BalanceSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    BalanceSheet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") BalanceSheet record, @Param("example") BalanceSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    int updateByExample(@Param("record") BalanceSheet record, @Param("example") BalanceSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    int updateByPrimaryKeySelective(BalanceSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    int updateByPrimaryKey(BalanceSheet record);
}