package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.CashFlowSheet;
import cn.ahyc.yjz.model.CashFlowSheetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CashFlowSheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    int countByExample(CashFlowSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    int deleteByExample(CashFlowSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    int insert(CashFlowSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    int insertSelective(CashFlowSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    List<CashFlowSheet> selectByExample(CashFlowSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    CashFlowSheet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") CashFlowSheet record, @Param("example") CashFlowSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    int updateByExample(@Param("record") CashFlowSheet record, @Param("example") CashFlowSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    int updateByPrimaryKeySelective(CashFlowSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_sheet
     *
     * @mbggenerated Mon Nov 16 10:09:39 CST 2015
     */
    int updateByPrimaryKey(CashFlowSheet record);
}