package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.Period;
import cn.ahyc.yjz.model.PeriodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PeriodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int countByExample(PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int deleteByExample(PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int insert(Period record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int insertSelective(Period record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    List<Period> selectByExample(PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    Period selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") Period record, @Param("example") PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByExample(@Param("record") Period record, @Param("example") PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByPrimaryKeySelective(Period record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByPrimaryKey(Period record);
}