package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.ProfitPeriod;
import cn.ahyc.yjz.model.ProfitPeriodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfitPeriodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    int countByExample(ProfitPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    int deleteByExample(ProfitPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    int insert(ProfitPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    int insertSelective(ProfitPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    List<ProfitPeriod> selectByExample(ProfitPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    ProfitPeriod selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProfitPeriod record, @Param("example") ProfitPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    int updateByExample(@Param("record") ProfitPeriod record, @Param("example") ProfitPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    int updateByPrimaryKeySelective(ProfitPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    int updateByPrimaryKey(ProfitPeriod record);
}