package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.VoucherDetail;
import cn.ahyc.yjz.model.VoucherDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoucherDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int countByExample(VoucherDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int deleteByExample(VoucherDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int insert(VoucherDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int insertSelective(VoucherDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    List<VoucherDetail> selectByExample(VoucherDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    VoucherDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") VoucherDetail record, @Param("example") VoucherDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByExample(@Param("record") VoucherDetail record, @Param("example") VoucherDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByPrimaryKeySelective(VoucherDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_detail
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    int updateByPrimaryKey(VoucherDetail record);
}