package cn.ahyc.yjz.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProfitPeriod implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.id
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.name
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.fix
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private Integer fix;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.month_exp
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private String monthExp;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.month_money
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private BigDecimal monthMoney;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.last_month_exp
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private String lastMonthExp;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.last_month_money
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private BigDecimal lastMonthMoney;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.book_id
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private Long bookId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.current_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private Integer currentPeriod;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.create_time
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column profit_period.modify_time
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public ProfitPeriod(Long id, String name, Integer fix, String monthExp, BigDecimal monthMoney, String lastMonthExp,
            BigDecimal lastMonthMoney, Long bookId, Integer currentPeriod, Date createTime, Date modifyTime) {
        this.id = id;
        this.name = name;
        this.fix = fix;
        this.monthExp = monthExp;
        this.monthMoney = monthMoney;
        this.lastMonthExp = lastMonthExp;
        this.lastMonthMoney = lastMonthMoney;
        this.bookId = bookId;
        this.currentPeriod = currentPeriod;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table profit_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public ProfitPeriod() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.id
     *
     * @return the value of profit_period.id
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.id
     *
     * @param id
     *            the value for profit_period.id
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.name
     *
     * @return the value of profit_period.name
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.name
     *
     * @param name
     *            the value for profit_period.name
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.fix
     *
     * @return the value of profit_period.fix
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public Integer getFix() {
        return fix;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.fix
     *
     * @param fix
     *            the value for profit_period.fix
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setFix(Integer fix) {
        this.fix = fix;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.month_exp
     *
     * @return the value of profit_period.month_exp
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public String getMonthExp() {
        return monthExp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.month_exp
     *
     * @param monthExp
     *            the value for profit_period.month_exp
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setMonthExp(String monthExp) {
        this.monthExp = monthExp == null ? null : monthExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.month_money
     *
     * @return the value of profit_period.month_money
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public BigDecimal getMonthMoney() {
        return monthMoney;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.month_money
     *
     * @param monthMoney
     *            the value for profit_period.month_money
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setMonthMoney(BigDecimal monthMoney) {
        this.monthMoney = monthMoney;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.last_month_exp
     *
     * @return the value of profit_period.last_month_exp
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public String getLastMonthExp() {
        return lastMonthExp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.last_month_exp
     *
     * @param lastMonthExp
     *            the value for profit_period.last_month_exp
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setLastMonthExp(String lastMonthExp) {
        this.lastMonthExp = lastMonthExp == null ? null : lastMonthExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.last_month_money
     *
     * @return the value of profit_period.last_month_money
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public BigDecimal getLastMonthMoney() {
        return lastMonthMoney;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.last_month_money
     *
     * @param lastMonthMoney
     *            the value for profit_period.last_month_money
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setLastMonthMoney(BigDecimal lastMonthMoney) {
        this.lastMonthMoney = lastMonthMoney;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.book_id
     *
     * @return the value of profit_period.book_id
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.book_id
     *
     * @param bookId
     *            the value for profit_period.book_id
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.current_period
     *
     * @return the value of profit_period.current_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public Integer getCurrentPeriod() {
        return currentPeriod;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.current_period
     *
     * @param currentPeriod
     *            the value for profit_period.current_period
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setCurrentPeriod(Integer currentPeriod) {
        this.currentPeriod = currentPeriod;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.create_time
     *
     * @return the value of profit_period.create_time
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.create_time
     *
     * @param createTime
     *            the value for profit_period.create_time
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column profit_period.modify_time
     *
     * @return the value of profit_period.modify_time
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column profit_period.modify_time
     *
     * @param modifyTime
     *            the value for profit_period.modify_time
     *
     * @mbggenerated Mon Nov 02 10:32:28 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}