-- MySQL Script generated by MySQL Workbench
-- Tue Sep 22 16:53:44 2015
-- Model: Database design for yijizhang    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yijizhang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `account_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account_book` ;

CREATE TABLE IF NOT EXISTS `account_book` (
  `id` BIGINT NOT NULL COMMENT '主键',
  `book_name` VARCHAR(128) NOT NULL COMMENT '账套名称',
  `money_code` VARCHAR(45) NULL COMMENT '记账本位币代码',
  `money_name` VARCHAR(45) NULL COMMENT '记账本位币名称',
  `start_time` DATE NULL COMMENT '账套启用日期',
  `init_year` INT NULL COMMENT '启用年',
  `init_period` INT NULL COMMENT '账套启用会计期间',
  `company_name` VARCHAR(128) NULL COMMENT '公司名称',
  `company_id` VARCHAR(45) NULL COMMENT '公司id',
  `dict_value_id` INT NOT NULL COMMENT '字典数据表id',
  `over_flag` INT NULL COMMENT '是否结束此次账套标示\n1  为结束    \n0  未结束',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '修改时间',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '账套表';


-- -----------------------------------------------------
-- Table `account_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account_subject` ;

CREATE TABLE IF NOT EXISTS `account_subject` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `subject_code` INT NOT NULL COMMENT '会计科目编码  \n暂定总分类：-1       小分类：0',
  `subject_name` VARCHAR(45) NOT NULL COMMENT '会计科目名称\n总分类与小分类填对应名称',
  `parent_subject_id` INT NOT NULL COMMENT '父会计科目id',
  `level` INT NOT NULL COMMENT '暂定总分类：-1   小分类：0\n会计科目一：1    会计科目二：2',
  `tip_info` VARCHAR(20) NULL COMMENT ' 助记码',
  `direction` INT NULL COMMENT '借方向 ：1     贷方向：2',
  `book_id` BIGINT NULL COMMENT '账套id',
  `total_debit` DECIMAL(11,2) NULL COMMENT '累计借方金额',
  `total_credit` DECIMAL(11,2) NULL COMMENT '累计贷方金额 ',
  `initial_left` DECIMAL(11,2) NULL COMMENT '期初余额',
  `year_occur_amount` DECIMAL(11,2) NULL COMMENT '本年累计损益实际发生额',
  `end_flag` INT NULL DEFAULT 0 COMMENT '是否结束此次账套标示/期结账\n1  结束   0  未结束',
  `base_flag` INT NULL DEFAULT 0 COMMENT '0：基础数据     1：非基础数据    ',
  `company_id` VARCHAR(45) NULL COMMENT '公司id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '修改时间',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_account_subject_account_book1_idx` (`book_id` ASC)  COMMENT '',
  CONSTRAINT `fk_account_subject_account_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `account_book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '会计科目表';


-- -----------------------------------------------------
-- Table `dict_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dict_type` ;

CREATE TABLE IF NOT EXISTS `dict_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `type_code` VARCHAR(45) NULL COMMENT '字典类型code，字典数据表外键',
  `type_name` VARCHAR(45) NULL COMMENT '字典类型名称',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '创建时间',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '字典类型表';


-- -----------------------------------------------------
-- Table `dict_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dict_value` ;

CREATE TABLE IF NOT EXISTS `dict_value` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `dict_type_id` BIGINT NULL COMMENT '字典类型code，字典数据表外键',
  `value` VARCHAR(45) NULL COMMENT '简称',
  `show_value` VARCHAR(45) NULL COMMENT '显示名字',
  `is_fixed` INT NULL COMMENT '是否固定，固定则不可修改  值：1\n不固定：0',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '修改时间',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_dict_value_dict_type1_idx` (`dict_type_id` ASC)  COMMENT '',
  CONSTRAINT `fk_dict_value_dict_type1`
    FOREIGN KEY (`dict_type_id`)
    REFERENCES `dict_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '字典数据表';


-- -----------------------------------------------------
-- Table `account_subject_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account_subject_template` ;

CREATE TABLE IF NOT EXISTS `account_subject_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `subject_code` INT NOT NULL COMMENT '会计科目编码  \n暂定总分类：-1       小分类：0',
  `subject_name` VARCHAR(128) NOT NULL COMMENT '会计科目名称\n总分类与小分类填对应名称',
  `parent_subject_id` INT NOT NULL COMMENT '父会计科目id',
  `level` INT NOT NULL COMMENT '暂定总分类：-1   小分类：0\n会计科目一：1    会计科目二：2',
  `balance_direction` INT NULL COMMENT '借方向 ：1     贷方向：2',
  `dict_value_id` INT NULL COMMENT '字段数据id，表示科目体系id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '修改时间',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '会计科目模板表';


-- -----------------------------------------------------
-- Table `period`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `period` ;

CREATE TABLE IF NOT EXISTS `period` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `start_time` TIMESTAMP NULL COMMENT '本期开始时间',
  `end_time` TIMESTAMP NULL COMMENT '本期结束时间',
  `current_period` INT NULL COMMENT '本期数值',
  `flag` INT NULL COMMENT '是否当前期    1 表示当前期   0   表示不是当前期',
  `book_id` BIGINT NULL COMMENT '账套id',
  `company_id` VARCHAR(45) NULL COMMENT '公司id',
  `end_flag` INT NULL COMMENT '表示此账套对应的期间是否可以修改\n1  为结束    \n0  未结束',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_period_account_book_idx` (`book_id` ASC)  COMMENT '',
  CONSTRAINT `fk_period_account_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `account_book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '期表';


-- -----------------------------------------------------
-- Table `voucher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voucher` ;

CREATE TABLE IF NOT EXISTS `voucher` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `voucher_word` VARCHAR(25) NULL COMMENT '凭证字',
  `voucher_no` INT NULL COMMENT '凭证号  必须唯一',
  `voucher_time` TIMESTAMP NULL COMMENT '日期',
  `bill_num` INT NULL COMMENT '附单据',
  `audit_user` VARCHAR(45) NULL COMMENT '审核人',
  `posting_user` VARCHAR(45) NULL COMMENT '过账人',
  `touching_user` VARCHAR(45) NULL COMMENT '制单人',
  `period_id` BIGINT NULL COMMENT '期间id',
  `company_id` VARCHAR(45) NULL COMMENT '',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '修改时间',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `accounting_no_UNIQUE` (`voucher_no` ASC)  COMMENT '',
  INDEX `fk_voucher_period1_idx` (`period_id` ASC)  COMMENT '',
  CONSTRAINT `fk_voucher_period1`
    FOREIGN KEY (`period_id`)
    REFERENCES `period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '记账凭证主表';


-- -----------------------------------------------------
-- Table `voucher_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voucher_detail` ;

CREATE TABLE IF NOT EXISTS `voucher_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `subject_code` INT NULL COMMENT '会计科目代码',
  `debit` DECIMAL(11,2) NULL COMMENT ' 借方金额',
  `credit` DECIMAL(11,2) NULL COMMENT '贷方金额',
  `summary` VARCHAR(200) NULL COMMENT '摘要',
  `voucher_id` BIGINT NULL COMMENT '记账主表id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '修改时间',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_voucher_detail_voucher1_idx` (`voucher_id` ASC)  COMMENT '',
  CONSTRAINT `fk_voucher_detail_voucher1`
    FOREIGN KEY (`voucher_id`)
    REFERENCES `voucher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '记账详细表';


-- -----------------------------------------------------
-- Table `company_common_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `company_common_type` ;

CREATE TABLE IF NOT EXISTS `company_common_type` (
  `id` BIGINT NOT NULL COMMENT '主键',
  `type_code` VARCHAR(45) NULL COMMENT '企业通用配置表code',
  `type_name` VARCHAR(45) NULL COMMENT '字典类型名称',
  `company_id` VARCHAR(45) NULL COMMENT '企业id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '创建时间',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '企业通用配置表';


-- -----------------------------------------------------
-- Table `company_common_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `company_common_value` ;

CREATE TABLE IF NOT EXISTS `company_common_value` (
  `id` BIGINT NOT NULL COMMENT '主键',
  `type_id` BIGINT NULL COMMENT '字典类型code，字典数据表外键',
  `value` VARCHAR(45) NULL COMMENT '简称',
  `show_value` VARCHAR(45) NULL COMMENT '显示名字',
  `company_id` VARCHAR(45) NULL COMMENT '企业id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '修改时间',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_company_common_value_company_common_type1_idx` (`type_id` ASC)  COMMENT '',
  CONSTRAINT `fk_company_common_value_company_common_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `company_common_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '企业通用配置值';


-- -----------------------------------------------------
-- Table `voucher_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voucher_template` ;

CREATE TABLE IF NOT EXISTS `voucher_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `voucher_word` VARCHAR(25) NULL COMMENT '凭证字',
  `bill_num` INT NULL COMMENT '附单据',
  `audit_user` VARCHAR(45) NULL COMMENT '审核人',
  `posting_user` VARCHAR(45) NULL COMMENT '过账人',
  `touching_user` VARCHAR(45) NULL COMMENT '制单人',
  `type_name` VARCHAR(45) NULL COMMENT '模板类别名称',
  `name` VARCHAR(45) NULL COMMENT '模板名称',
  `company_id` VARCHAR(45) NULL COMMENT '企业id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '修改时间',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '记账凭证模板主表';


-- -----------------------------------------------------
-- Table `voucher_template_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voucher_template_detail` ;

CREATE TABLE IF NOT EXISTS `voucher_template_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `summary` VARCHAR(200) NULL COMMENT '摘要',
  `subject_code` INT NULL COMMENT '会计科目代码',
  `debit` DECIMAL(11,2) NULL COMMENT ' 借方金额',
  `credit` DECIMAL(11,2) NULL COMMENT '贷方金额',
  `template_id` BIGINT NULL COMMENT '记账主表id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_voucher_template_detail_voucher_template1_idx` (`template_id` ASC)  COMMENT '',
  CONSTRAINT `fk_voucher_template_detail_voucher_template1`
    FOREIGN KEY (`template_id`)
    REFERENCES `voucher_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '记账模板详细表';


-- -----------------------------------------------------
-- Table `subject_length`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subject_length` ;

CREATE TABLE IF NOT EXISTS `subject_length` (
  `id` BIGINT NOT NULL COMMENT ' 主键',
  `length` INT NULL COMMENT '',
  `level` INT NULL COMMENT '层级',
  `book_id` BIGINT NULL COMMENT '账套id',
  `company_id` VARCHAR(45) NULL COMMENT '企业id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `modify_time` TIMESTAMP NOT NULL DEFAULT "2015-01-01 00:00:00" COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_subject_length_account_book1_idx` (`book_id` ASC)  COMMENT '',
  CONSTRAINT `fk_subject_length_account_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `account_book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '定义会计科目长度表';


DELIMITER $$

DROP TRIGGER IF EXISTS `account_book_BEFORE_UPDATE` $$
CREATE TRIGGER `account_book_BEFORE_UPDATE` BEFORE UPDATE ON `account_book` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `account_subject_BEFORE_UPDATE` $$
CREATE TRIGGER `account_subject_BEFORE_UPDATE` BEFORE UPDATE ON `account_subject` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `dict_type_BEFORE_UPDATE` $$
CREATE TRIGGER `dict_type_BEFORE_UPDATE` BEFORE UPDATE ON `dict_type` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `dict_value_BEFORE_UPDATE` $$
CREATE TRIGGER `dict_value_BEFORE_UPDATE` BEFORE UPDATE ON `dict_value` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `account_subject_template_BEFORE_UPDATE` $$
CREATE TRIGGER `account_subject_template_BEFORE_UPDATE` BEFORE UPDATE ON `account_subject_template` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `period_BEFORE_UPDATE` $$
CREATE TRIGGER `period_BEFORE_UPDATE` BEFORE UPDATE ON `period` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `voucher_BEFORE_UPDATE` $$
CREATE TRIGGER `voucher_BEFORE_UPDATE` BEFORE UPDATE ON `voucher` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `voucher_detail_BEFORE_UPDATE` $$
CREATE TRIGGER `voucher_detail_BEFORE_UPDATE` BEFORE UPDATE ON `voucher_detail` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `company_common_type_BEFORE_UPDATE` $$
CREATE TRIGGER `company_common_type_BEFORE_UPDATE` BEFORE UPDATE ON `company_common_type` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `company_common_value_BEFORE_UPDATE` $$
CREATE TRIGGER `company_common_value_BEFORE_UPDATE` BEFORE UPDATE ON `company_common_value` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `voucher_template_BEFORE_UPDATE` $$
CREATE TRIGGER `voucher_template_BEFORE_UPDATE` BEFORE UPDATE ON `voucher_template` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `voucher_template_detail_BEFORE_UPDATE` $$
CREATE TRIGGER `voucher_template_detail_BEFORE_UPDATE` BEFORE UPDATE ON `voucher_template_detail` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DROP TRIGGER IF EXISTS `subject_length_BEFORE_UPDATE` $$
CREATE TRIGGER `subject_length_BEFORE_UPDATE` BEFORE UPDATE ON `subject_length` FOR EACH ROW
BEGIN
	SET NEW.`modify_time` = NOW();
END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
