package cn.ahyc.yjz.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccountSubjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public AccountSubjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeIsNull() {
            addCriterion("subject_code is null");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeIsNotNull() {
            addCriterion("subject_code is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeEqualTo(Long value) {
            addCriterion("subject_code =", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeNotEqualTo(Long value) {
            addCriterion("subject_code <>", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeGreaterThan(Long value) {
            addCriterion("subject_code >", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("subject_code >=", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeLessThan(Long value) {
            addCriterion("subject_code <", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeLessThanOrEqualTo(Long value) {
            addCriterion("subject_code <=", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeIn(List<Long> values) {
            addCriterion("subject_code in", values, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeNotIn(List<Long> values) {
            addCriterion("subject_code not in", values, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeBetween(Long value1, Long value2) {
            addCriterion("subject_code between", value1, value2, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeNotBetween(Long value1, Long value2) {
            addCriterion("subject_code not between", value1, value2, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNull() {
            addCriterion("subject_name is null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNotNull() {
            addCriterion("subject_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameEqualTo(String value) {
            addCriterion("subject_name =", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotEqualTo(String value) {
            addCriterion("subject_name <>", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThan(String value) {
            addCriterion("subject_name >", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("subject_name >=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThan(String value) {
            addCriterion("subject_name <", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThanOrEqualTo(String value) {
            addCriterion("subject_name <=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLike(String value) {
            addCriterion("subject_name like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotLike(String value) {
            addCriterion("subject_name not like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIn(List<String> values) {
            addCriterion("subject_name in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotIn(List<String> values) {
            addCriterion("subject_name not in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameBetween(String value1, String value2) {
            addCriterion("subject_name between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotBetween(String value1, String value2) {
            addCriterion("subject_name not between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeIsNull() {
            addCriterion("parent_subject_code is null");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeIsNotNull() {
            addCriterion("parent_subject_code is not null");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeEqualTo(Long value) {
            addCriterion("parent_subject_code =", value, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeNotEqualTo(Long value) {
            addCriterion("parent_subject_code <>", value, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeGreaterThan(Long value) {
            addCriterion("parent_subject_code >", value, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_subject_code >=", value, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeLessThan(Long value) {
            addCriterion("parent_subject_code <", value, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeLessThanOrEqualTo(Long value) {
            addCriterion("parent_subject_code <=", value, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeIn(List<Long> values) {
            addCriterion("parent_subject_code in", values, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeNotIn(List<Long> values) {
            addCriterion("parent_subject_code not in", values, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeBetween(Long value1, Long value2) {
            addCriterion("parent_subject_code between", value1, value2, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andParentSubjectCodeNotBetween(Long value1, Long value2) {
            addCriterion("parent_subject_code not between", value1, value2, "parentSubjectCode");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andTipInfoIsNull() {
            addCriterion("tip_info is null");
            return (Criteria) this;
        }

        public Criteria andTipInfoIsNotNull() {
            addCriterion("tip_info is not null");
            return (Criteria) this;
        }

        public Criteria andTipInfoEqualTo(String value) {
            addCriterion("tip_info =", value, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoNotEqualTo(String value) {
            addCriterion("tip_info <>", value, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoGreaterThan(String value) {
            addCriterion("tip_info >", value, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoGreaterThanOrEqualTo(String value) {
            addCriterion("tip_info >=", value, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoLessThan(String value) {
            addCriterion("tip_info <", value, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoLessThanOrEqualTo(String value) {
            addCriterion("tip_info <=", value, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoLike(String value) {
            addCriterion("tip_info like", value, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoNotLike(String value) {
            addCriterion("tip_info not like", value, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoIn(List<String> values) {
            addCriterion("tip_info in", values, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoNotIn(List<String> values) {
            addCriterion("tip_info not in", values, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoBetween(String value1, String value2) {
            addCriterion("tip_info between", value1, value2, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andTipInfoNotBetween(String value1, String value2) {
            addCriterion("tip_info not between", value1, value2, "tipInfo");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("direction is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("direction is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(Integer value) {
            addCriterion("direction =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(Integer value) {
            addCriterion("direction <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(Integer value) {
            addCriterion("direction >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(Integer value) {
            addCriterion("direction >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(Integer value) {
            addCriterion("direction <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(Integer value) {
            addCriterion("direction <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<Integer> values) {
            addCriterion("direction in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<Integer> values) {
            addCriterion("direction not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(Integer value1, Integer value2) {
            addCriterion("direction between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(Integer value1, Integer value2) {
            addCriterion("direction not between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNull() {
            addCriterion("book_id is null");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNotNull() {
            addCriterion("book_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookIdEqualTo(Long value) {
            addCriterion("book_id =", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotEqualTo(Long value) {
            addCriterion("book_id <>", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThan(Long value) {
            addCriterion("book_id >", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThanOrEqualTo(Long value) {
            addCriterion("book_id >=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThan(Long value) {
            addCriterion("book_id <", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThanOrEqualTo(Long value) {
            addCriterion("book_id <=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdIn(List<Long> values) {
            addCriterion("book_id in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotIn(List<Long> values) {
            addCriterion("book_id not in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdBetween(Long value1, Long value2) {
            addCriterion("book_id between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotBetween(Long value1, Long value2) {
            addCriterion("book_id not between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andTotalDebitIsNull() {
            addCriterion("total_debit is null");
            return (Criteria) this;
        }

        public Criteria andTotalDebitIsNotNull() {
            addCriterion("total_debit is not null");
            return (Criteria) this;
        }

        public Criteria andTotalDebitEqualTo(BigDecimal value) {
            addCriterion("total_debit =", value, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalDebitNotEqualTo(BigDecimal value) {
            addCriterion("total_debit <>", value, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalDebitGreaterThan(BigDecimal value) {
            addCriterion("total_debit >", value, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalDebitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_debit >=", value, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalDebitLessThan(BigDecimal value) {
            addCriterion("total_debit <", value, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalDebitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_debit <=", value, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalDebitIn(List<BigDecimal> values) {
            addCriterion("total_debit in", values, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalDebitNotIn(List<BigDecimal> values) {
            addCriterion("total_debit not in", values, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalDebitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_debit between", value1, value2, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalDebitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_debit not between", value1, value2, "totalDebit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditIsNull() {
            addCriterion("total_credit is null");
            return (Criteria) this;
        }

        public Criteria andTotalCreditIsNotNull() {
            addCriterion("total_credit is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCreditEqualTo(BigDecimal value) {
            addCriterion("total_credit =", value, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditNotEqualTo(BigDecimal value) {
            addCriterion("total_credit <>", value, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditGreaterThan(BigDecimal value) {
            addCriterion("total_credit >", value, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_credit >=", value, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditLessThan(BigDecimal value) {
            addCriterion("total_credit <", value, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_credit <=", value, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditIn(List<BigDecimal> values) {
            addCriterion("total_credit in", values, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditNotIn(List<BigDecimal> values) {
            addCriterion("total_credit not in", values, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_credit between", value1, value2, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andTotalCreditNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_credit not between", value1, value2, "totalCredit");
            return (Criteria) this;
        }

        public Criteria andInitialLeftIsNull() {
            addCriterion("initial_left is null");
            return (Criteria) this;
        }

        public Criteria andInitialLeftIsNotNull() {
            addCriterion("initial_left is not null");
            return (Criteria) this;
        }

        public Criteria andInitialLeftEqualTo(BigDecimal value) {
            addCriterion("initial_left =", value, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andInitialLeftNotEqualTo(BigDecimal value) {
            addCriterion("initial_left <>", value, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andInitialLeftGreaterThan(BigDecimal value) {
            addCriterion("initial_left >", value, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andInitialLeftGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("initial_left >=", value, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andInitialLeftLessThan(BigDecimal value) {
            addCriterion("initial_left <", value, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andInitialLeftLessThanOrEqualTo(BigDecimal value) {
            addCriterion("initial_left <=", value, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andInitialLeftIn(List<BigDecimal> values) {
            addCriterion("initial_left in", values, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andInitialLeftNotIn(List<BigDecimal> values) {
            addCriterion("initial_left not in", values, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andInitialLeftBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("initial_left between", value1, value2, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andInitialLeftNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("initial_left not between", value1, value2, "initialLeft");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountIsNull() {
            addCriterion("year_occur_amount is null");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountIsNotNull() {
            addCriterion("year_occur_amount is not null");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountEqualTo(BigDecimal value) {
            addCriterion("year_occur_amount =", value, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountNotEqualTo(BigDecimal value) {
            addCriterion("year_occur_amount <>", value, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountGreaterThan(BigDecimal value) {
            addCriterion("year_occur_amount >", value, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("year_occur_amount >=", value, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountLessThan(BigDecimal value) {
            addCriterion("year_occur_amount <", value, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("year_occur_amount <=", value, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountIn(List<BigDecimal> values) {
            addCriterion("year_occur_amount in", values, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountNotIn(List<BigDecimal> values) {
            addCriterion("year_occur_amount not in", values, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("year_occur_amount between", value1, value2, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andYearOccurAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("year_occur_amount not between", value1, value2, "yearOccurAmount");
            return (Criteria) this;
        }

        public Criteria andEndFlagIsNull() {
            addCriterion("end_flag is null");
            return (Criteria) this;
        }

        public Criteria andEndFlagIsNotNull() {
            addCriterion("end_flag is not null");
            return (Criteria) this;
        }

        public Criteria andEndFlagEqualTo(Integer value) {
            addCriterion("end_flag =", value, "endFlag");
            return (Criteria) this;
        }

        public Criteria andEndFlagNotEqualTo(Integer value) {
            addCriterion("end_flag <>", value, "endFlag");
            return (Criteria) this;
        }

        public Criteria andEndFlagGreaterThan(Integer value) {
            addCriterion("end_flag >", value, "endFlag");
            return (Criteria) this;
        }

        public Criteria andEndFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("end_flag >=", value, "endFlag");
            return (Criteria) this;
        }

        public Criteria andEndFlagLessThan(Integer value) {
            addCriterion("end_flag <", value, "endFlag");
            return (Criteria) this;
        }

        public Criteria andEndFlagLessThanOrEqualTo(Integer value) {
            addCriterion("end_flag <=", value, "endFlag");
            return (Criteria) this;
        }

        public Criteria andEndFlagIn(List<Integer> values) {
            addCriterion("end_flag in", values, "endFlag");
            return (Criteria) this;
        }

        public Criteria andEndFlagNotIn(List<Integer> values) {
            addCriterion("end_flag not in", values, "endFlag");
            return (Criteria) this;
        }

        public Criteria andEndFlagBetween(Integer value1, Integer value2) {
            addCriterion("end_flag between", value1, value2, "endFlag");
            return (Criteria) this;
        }

        public Criteria andEndFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("end_flag not between", value1, value2, "endFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagIsNull() {
            addCriterion("base_flag is null");
            return (Criteria) this;
        }

        public Criteria andBaseFlagIsNotNull() {
            addCriterion("base_flag is not null");
            return (Criteria) this;
        }

        public Criteria andBaseFlagEqualTo(Integer value) {
            addCriterion("base_flag =", value, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagNotEqualTo(Integer value) {
            addCriterion("base_flag <>", value, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagGreaterThan(Integer value) {
            addCriterion("base_flag >", value, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("base_flag >=", value, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagLessThan(Integer value) {
            addCriterion("base_flag <", value, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagLessThanOrEqualTo(Integer value) {
            addCriterion("base_flag <=", value, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagIn(List<Integer> values) {
            addCriterion("base_flag in", values, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagNotIn(List<Integer> values) {
            addCriterion("base_flag not in", values, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagBetween(Integer value1, Integer value2) {
            addCriterion("base_flag between", value1, value2, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andBaseFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("base_flag not between", value1, value2, "baseFlag");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account_subject
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 30 16:20:19 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 30 16:20:19 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}