package cn.ahyc.yjz.model;

import java.io.Serializable;
import java.util.Date;

public class ActionLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.id
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.action
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.states
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private String states;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.description
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.operator
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.address
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.os
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.pc_name
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private String pcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.action_time
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private Date actionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.method_name
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_log
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public ActionLog(Long id, String action, String states, String description, String operator, String address, String os, String pcName, Date actionTime, String methodName) {
        this.id = id;
        this.action = action;
        this.states = states;
        this.description = description;
        this.operator = operator;
        this.address = address;
        this.os = os;
        this.pcName = pcName;
        this.actionTime = actionTime;
        this.methodName = methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public ActionLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.id
     *
     * @return the value of action_log.id
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.id
     *
     * @param id the value for action_log.id
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.action
     *
     * @return the value of action_log.action
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.action
     *
     * @param action the value for action_log.action
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.states
     *
     * @return the value of action_log.states
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public String getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.states
     *
     * @param states the value for action_log.states
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setStates(String states) {
        this.states = states == null ? null : states.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.description
     *
     * @return the value of action_log.description
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.description
     *
     * @param description the value for action_log.description
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.operator
     *
     * @return the value of action_log.operator
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.operator
     *
     * @param operator the value for action_log.operator
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.address
     *
     * @return the value of action_log.address
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.address
     *
     * @param address the value for action_log.address
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.os
     *
     * @return the value of action_log.os
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.os
     *
     * @param os the value for action_log.os
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.pc_name
     *
     * @return the value of action_log.pc_name
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public String getPcName() {
        return pcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.pc_name
     *
     * @param pcName the value for action_log.pc_name
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setPcName(String pcName) {
        this.pcName = pcName == null ? null : pcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.action_time
     *
     * @return the value of action_log.action_time
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public Date getActionTime() {
        return actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.action_time
     *
     * @param actionTime the value for action_log.action_time
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setActionTime(Date actionTime) {
        this.actionTime = actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.method_name
     *
     * @return the value of action_log.method_name
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.method_name
     *
     * @param methodName the value for action_log.method_name
     *
     * @mbggenerated Wed Oct 14 14:16:00 CST 2015
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }
}