package cn.ahyc.yjz.model;

import java.io.Serializable;
import java.util.Date;

public class BalanceSheet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.id
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.code
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.parent_code
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private Long parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.name
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.year_begin_exp
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private String yearBeginExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.period_end_exp
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private String periodEndExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.need_sum
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private Integer needSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.level
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.create_time
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_sheet.modify_time
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public BalanceSheet(Long id, Long code, Long parentCode, String name, String yearBeginExp, String periodEndExp, Integer needSum, Integer level, Date createTime, Date modifyTime) {
        this.id = id;
        this.code = code;
        this.parentCode = parentCode;
        this.name = name;
        this.yearBeginExp = yearBeginExp;
        this.periodEndExp = periodEndExp;
        this.needSum = needSum;
        this.level = level;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_sheet
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public BalanceSheet() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.id
     *
     * @return the value of balance_sheet.id
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.id
     *
     * @param id the value for balance_sheet.id
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.code
     *
     * @return the value of balance_sheet.code
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.code
     *
     * @param code the value for balance_sheet.code
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.parent_code
     *
     * @return the value of balance_sheet.parent_code
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public Long getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.parent_code
     *
     * @param parentCode the value for balance_sheet.parent_code
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setParentCode(Long parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.name
     *
     * @return the value of balance_sheet.name
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.name
     *
     * @param name the value for balance_sheet.name
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.year_begin_exp
     *
     * @return the value of balance_sheet.year_begin_exp
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public String getYearBeginExp() {
        return yearBeginExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.year_begin_exp
     *
     * @param yearBeginExp the value for balance_sheet.year_begin_exp
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setYearBeginExp(String yearBeginExp) {
        this.yearBeginExp = yearBeginExp == null ? null : yearBeginExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.period_end_exp
     *
     * @return the value of balance_sheet.period_end_exp
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public String getPeriodEndExp() {
        return periodEndExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.period_end_exp
     *
     * @param periodEndExp the value for balance_sheet.period_end_exp
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setPeriodEndExp(String periodEndExp) {
        this.periodEndExp = periodEndExp == null ? null : periodEndExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.need_sum
     *
     * @return the value of balance_sheet.need_sum
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public Integer getNeedSum() {
        return needSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.need_sum
     *
     * @param needSum the value for balance_sheet.need_sum
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setNeedSum(Integer needSum) {
        this.needSum = needSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.level
     *
     * @return the value of balance_sheet.level
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.level
     *
     * @param level the value for balance_sheet.level
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.create_time
     *
     * @return the value of balance_sheet.create_time
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.create_time
     *
     * @param createTime the value for balance_sheet.create_time
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_sheet.modify_time
     *
     * @return the value of balance_sheet.modify_time
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_sheet.modify_time
     *
     * @param modifyTime the value for balance_sheet.modify_time
     *
     * @mbggenerated Fri Oct 16 13:11:38 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}