package cn.ahyc.yjz.model;

import java.io.Serializable;
import java.util.Date;

public class ProfitTemplate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit_template.id
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit_template.name
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit_template.month_exp
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    private String monthExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit_template.last_month_exp
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    private String lastMonthExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit_template.create_time
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit_template.modify_time
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table profit_template
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_template
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public ProfitTemplate(Long id, String name, String monthExp, String lastMonthExp, Date createTime, Date modifyTime) {
        this.id = id;
        this.name = name;
        this.monthExp = monthExp;
        this.lastMonthExp = lastMonthExp;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_template
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public ProfitTemplate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit_template.id
     *
     * @return the value of profit_template.id
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit_template.id
     *
     * @param id the value for profit_template.id
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit_template.name
     *
     * @return the value of profit_template.name
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit_template.name
     *
     * @param name the value for profit_template.name
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit_template.month_exp
     *
     * @return the value of profit_template.month_exp
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public String getMonthExp() {
        return monthExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit_template.month_exp
     *
     * @param monthExp the value for profit_template.month_exp
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public void setMonthExp(String monthExp) {
        this.monthExp = monthExp == null ? null : monthExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit_template.last_month_exp
     *
     * @return the value of profit_template.last_month_exp
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public String getLastMonthExp() {
        return lastMonthExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit_template.last_month_exp
     *
     * @param lastMonthExp the value for profit_template.last_month_exp
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public void setLastMonthExp(String lastMonthExp) {
        this.lastMonthExp = lastMonthExp == null ? null : lastMonthExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit_template.create_time
     *
     * @return the value of profit_template.create_time
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit_template.create_time
     *
     * @param createTime the value for profit_template.create_time
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit_template.modify_time
     *
     * @return the value of profit_template.modify_time
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit_template.modify_time
     *
     * @param modifyTime the value for profit_template.modify_time
     *
     * @mbggenerated Mon Nov 02 09:17:12 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}